package com.ullas.com.jQueryevaluator.constants;

public class TestCaseConstants {

  public static final String testCase1Rule = "{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"amount\",\n"
      + "            \"field\": \"amount\",\n"
      + "            \"type\": \"double\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"greater\",\n"
      + "            \"value\": 50.00\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}}";

  public static final String testCase2Rule = "{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"circle\",\n"
      + "            \"field\": \"circle\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 10\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}";

  public static String testCase3Rule = "{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"base_plan\",\n"
      + "            \"field\": \"base_plan\",\n"
      + "            \"type\": \"string\",\n"
      + "            \"input\": \"text\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": \"4g_data\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}";
  public static String testCase4Rule = "{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"circle\",\n"
      + "            \"field\": \"circle\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 10\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"amount\",\n"
      + "            \"field\": \"amount\",\n"
      + "            \"type\": \"double\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"less_or_equal\",\n"
      + "            \"value\": 100.0\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}";
  public static String testCase5Rule = "{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"circle\",\n"
      + "            \"field\": \"circle\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 10\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"base_plan\",\n"
      + "            \"field\": \"base_plan\",\n"
      + "            \"type\": \"string\",\n"
      + "            \"input\": \"text\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": \"4g_data\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}";
  public static String testCase6Rule ="{\n"
      + "    \"condition\": \"AND\",\n"
      + "    \"rules\": [\n"
      + "        {\n"
      + "            \"id\": \"operator\",\n"
      + "            \"field\": \"operator\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"circle\",\n"
      + "            \"field\": \"circle\",\n"
      + "            \"type\": \"integer\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": 5\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": \"amount\",\n"
      + "            \"field\": \"amount\",\n"
      + "            \"type\": \"double\",\n"
      + "            \"input\": \"number\",\n"
      + "            \"operator\": \"greater_or_equal\",\n"
      + "            \"value\": 50.00\n"
      + "        },\n"
      + "         {\n"
      + "            \"id\": \"base_plan\",\n"
      + "            \"field\": \"base_plan\",\n"
      + "            \"type\": \"string\",\n"
      + "            \"input\": \"string\",\n"
      + "            \"operator\": \"equal\",\n"
      + "            \"value\": \"4g\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"valid\": true\n"
      + "}";
}
