name: Publishes new Artifacts to GitHub
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: build & Test stage
        run: ./gradlew clean build

      - name: publish stage
        run: ./gradlew publish -Pversion=${GITHUB_REF#refs/*/}
